name: Build React App and Deploy to Firebase hosting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install NPM packages
      run: npm ci
      
    - name: Build React app
      run: npm run build
      env:
        REACT_APP_LIFF_ID: ${{ secret.REACT_APP_LIFF_ID }}
        BASE_URL: ${{ secret.BASE_URL }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: asamit-out
        path: ./dist
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: create out directory
        run: mkdir dist
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: asamit-out
          path: ./dist
      - name: Display downloaded directory
        run: |
          ls
      - name: deploy to firebase hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with: 
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ASAMI_1E0C2 }}'
          channelId: 'live'
          target: 'main'
